# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-07 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20180205_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='media/portadas'),
        ),
    ]
