# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-20 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
